package com.meitu.greendaohelper;
// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BIAN_KUANG_ENTITY.
 */
public class BianKuangEntity {

    private Long id;
    /** Not-null value. */
    private String imageName;
    /** Not-null value. */
    private String imageNameThumb;

    public BianKuangEntity() {
    }

    public BianKuangEntity(Long id) {
        this.id = id;
    }

    public BianKuangEntity(Long id, String imageName, String imageNameThumb) {
        this.id = id;
        this.imageName = imageName;
        this.imageNameThumb = imageNameThumb;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getImageName() {
        return imageName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setImageName(String imageName) {
        this.imageName = imageName;
    }

    /** Not-null value. */
    public String getImageNameThumb() {
        return imageNameThumb;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setImageNameThumb(String imageNameThumb) {
        this.imageNameThumb = imageNameThumb;
    }

}
